# -*- coding: utf-8 -*-
"""project 1 Dimas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U9y4sHDUfGnQsJf7jFAtDkdRjDJCD54M
"""

# Data mahasiswa (nama: (tugas, uts, uas))
mahasiswa = {
    "Andi": (80, 85, 90),
    "Budi": (90, 88, 92),
    "Citra": (75, 70, 80),
    "Deni": (60, 65, 70),
    "Eka": (85, 80, 88)
}

nilai_tertinggi = 0
nama_tertinggi = ""

for nama, nilai in mahasiswa.items():
    tugas, uts, uas = nilai

    # hitung nilai akhir
    nilai_akhir = (0.3 * tugas) + (0.3 * uts) + (0.4 * uas)

    # tentukan grade
    if nilai_akhir >= 85:
        grade = "A"
    elif nilai_akhir >= 70:
        grade = "B"
    elif nilai_akhir >= 60:
        grade = "C"
    else:
        grade = "D"

    print(f"{nama}: {nilai_akhir:.1f} ({grade})")

    # cek nilai tertinggi
    if nilai_akhir > nilai_tertinggi:
        nilai_tertinggi = nilai_akhir
        nama_tertinggi = nama

print(f"\nNilai tertinggi: {nama_tertinggi} ({nilai_tertinggi:.1f})")









# Data barang (nama: (harga, stok))
barang = {
    "Laptop": (7000000, 5),
    "Mouse": (100000, 20),
    "Keyboard": (300000, 10),
    "Monitor": (2000000, 3),
    "Flashdisk": (50000, 50)
}

total_inventaris = 0

stok_min = float('inf')
barang_stok_min = ""

harga_max = 0
barang_harga_max = ""

# tampilkan data
for nama, data in barang.items():
    harga, stok = data

    print(f"{nama} - Harga: {harga}, Stok: {stok}")

    # hitung total inventaris
    total_inventaris += harga * stok

    # cek stok paling sedikit
    if stok < stok_min:
        stok_min = stok
        barang_stok_min = nama

    # cek harga paling mahal
    if harga > harga_max:
        harga_max = harga
        barang_harga_max = nama

print(f"\nTotal nilai inventaris: {total_inventaris}")
print(f"Stok paling sedikit: {barang_stok_min} ({stok_min})")
print(f"Harga paling mahal: {barang_harga_max} ({harga_max})")